baseurl: "/natural"
url: "https://camilocuspian.github.io"
title: "Natural One Live"
telefono: ""
whatsapp: ""
email: ""
maps: https://maps.app.goo.gl/LAmA8gQZFBxwKak28

markdown: kramdown

permalink: :slug

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore: []
  envs: []
  blanklines: false
  profile: false
  startings: []

collections:
  posts:
    output: true
    permalink: /blog/:slug

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
